---
image: Ubuntu
build_script:
  - whoami
  - pwd
  - ls -al
  - ls -al /usr/lib/jvm/
  - java -version
  - sudo update-alternatives --set java /usr/lib/jvm/java-14-openjdk-amd64/bin/java
  - java -version
  - ./gradlew build
artifacts:
  - name: warfile
    path: 'build\libs\*.war'
deploy:
  description: Latest stable release
  provider: GitHub
  auth_token:
    secure: TjyyWBvqvk2/j05cBmpMpWsBslEdpJV2JOWy/5Uwr7IP1zKVMx/x97deqVskxx6L
  artifact: warfile
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
