---
sudo: required
services:
  - docker
script:
  - 'DOCKER_IMAGE=ftm-web-view'
  - 'docker build -t $DOCKER_IMAGE .'
after_success:
  - 'echo $DOCKER_IMAGE'
  - 'docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN'
  - 'docker tag $DOCKER_IMAGE $DOCKER_USERNAME/$DOCKER_IMAGE:latest'
  - 'docker push $DOCKER_USERNAME/$DOCKER_IMAGE:latest'
