plugins {
    id 'java-library'
    id 'war'
}

version = '1.2.2'

group = 'nu.mine.mosher.genealogy'

repositories {
    mavenCentral()
    google()
    maven {
        url = uri('https://public:\u0067hp_fya6Kseu3XOBMg2icbg7f1LP6ZFYjj35v4Zj@maven.pkg.github.com/cmosher01/*')
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of 25
        vendor = JvmVendorSpec.ADOPTIUM
    }
}

compileJava {
    options.compilerArgs << '-parameters'
}

test {
    useJUnitPlatform()
}

dependencies {
    implementation 'org.xerial:sqlite-jdbc:latest.release'
    implementation 'org.liquibase:liquibase-core:latest.release'
    implementation 'org.mybatis:mybatis:latest.release'
    implementation 'com.google.api-client:google-api-client:latest.release'
    implementation 'nu.mine.mosher.xml:tei-to-xhtml5:latest.integration'
    implementation 'nu.mine.mosher.xml:xslt-pipeline:latest.integration'
    providedCompile 'jakarta.servlet:jakarta.servlet-api:6.1.0'

    implementation 'org.slf4j:slf4j-api:latest.release'
    runtimeOnly 'org.slf4j:slf4j-jdk14:latest.release'
    runtimeOnly 'org.slf4j:log4j-over-slf4j:latest.release'
    runtimeOnly 'org.slf4j:jcl-over-slf4j:latest.release'

    implementation 'org.apache.tika:tika-parsers:1.+', {
        exclude group: 'org.slf4j', module: 'jul-to-slf4j'
    }
    implementation 'org.jsoup:jsoup:latest.release'
    implementation 'org.nibor.autolink:autolink:latest.release'

    runtimeOnly 'xerces:xercesImpl:latest.release', {
        exclude group: 'xml-apis'
    }
    runtimeOnly 'net.sf.saxon:Saxon-HE:latest.release'

    implementation 'org.apache.httpcomponents.client5:httpclient5:latest.release'



    testImplementation 'org.junit.jupiter:junit-jupiter:latest.release'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
