# This Docker Compose file is for local testing during development only.
# The Dockerfile, however, is the production image.

volumes:
  db:

services:
  proxy:
    image: 'nginx'
    volumes:
      - './src/main/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './example:/srv:ro'
    ports:
      - '60080:80'

  webserver:
    build: './'
    environment:
      ftm_dir: '/srv'
      CLIENT_ID: "${CLIENT_ID}"
      ftm_public_access: 'public'
      FTM_COPYRIGHT: "Copyright © 2022, by John Doe, Anytown, USA."
      FTM_AUTHOR: "John Doe"
    volumes:
      - './example:/srv:ro'
      - 'db:/root'

  sqlite:
    image: 'ttimbers/ubuntu-sqlite3'
    platform: 'linux/amd64'
    command: 'bash -c "sleep 7d"'
    volumes:
      - 'db:/root'
