version: '3'

services:
  proxy:
    image: 'nginx'
    volumes:
      - './src/main/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './example:/srv:ro'
    ports:
      - '60080:80'

  webserver:
    build: './'
    environment:
      ftm_dir: '/srv'
      CLIENT_ID: "${CLIENT_ID}"
      ftm_public_access: 'public'
      FTM_COPYRIGHT: "Copyright © 2022, by John Doe, Anytown, USA."
      FTM_AUTHOR: "John Doe"
    volumes:
      - './example:/srv:ro'
