version: '3'

services:
  proxy:
    image: 'nginx'
    volumes:
      - './src/main/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './example:/srv:ro'
    ports:
      - '60080:80'

  webserver:
    build: './'
    environment:
      ftm_dir: '/srv'
      CLIENT_ID: "${CLIENT_ID}"
    volumes:
      - './example:/srv:ro'
